--THE DATA REPRESENTS SALES DATA FOR AN ONLINE RETAIL SHOP FOR THE YEARS 2010 AND 2011. 
--IT WAS DATA FROM A VIRTUAL INTERNSHIP EXPERIENCE BY FORAGE IN DATA VISUALIZATION.
--THE DATA WAS CLEANED IN EXCEL AND WAS VISUALISED IN TABLEAU
--HOWEVER WANT TO DO THE SAME DATA CLEANING AND EXPLORATION IN SQL

--FIRST WE SELECT THE ENTIRE DATA


SELECT *
FROM [dbo].[Online Retail]

--WE THEN SELECT THE ROWS THAT HAVE BLANK CUSTOMER IDs. THIS MEANS THAT THEY ARE NOT ACTUAL PURCHASES BECAUSE EVERY PURCHASE HAS A CUSTOMER ID

SELECT *
FROM [dbo].[Online Retail]
WHERE CustomerID IS NULL

DELETE
FROM [dbo].[Online Retail]
WHERE CustomerID IS NULL     --THIS REMOVES THE ROWS WITH BLANK CUSTOMER IDs FROM THE TABLE


--WE GO ON TO SELECT ITEMS WITH PRICES AND QUANTITIES LESS THAN 1

SELECT *
FROM [dbo].[Online Retail]
WHERE Quantity <1

DELETE 
FROM [dbo].[Online Retail]
WHERE Quantity <1            --THIS DELETES THE ROWS WITH QUANTITIES LESS THAN 1


--NOW THAT OUR DATA IS CLEAN AND READY FOR USE, WE LOOK AT THE REVENUE GENERATED EACH MONTH THROUGHOUT THE YEAR 2011

SELECT  Month, ROUND(SUM(Revenue),0)  AS rev_sum
FROM [dbo].[Online Retail]
WHERE Year = 2011
GROUP BY Month
ORDER BY rev_sum DESC         --FROM THIS WE CAN TELL THAT WE HAD THE HIGHEST REVENUE IN NOVEMBER WITH 1.16 MILLION

--THE NEXT IS TO LOOK AT THE TOP 10 COUNTRIES ASIDE UNITED KINGDOM THAT PROVIDED THE HIGHEST REVENUE FOR THE ENTIRE PERIOD OF THE DATA (2010 AND 2011)

SELECT TOP(10) Country, ROUND(SUM(Revenue),0) AS country_rev
FROM [dbo].[Online Retail]
WHERE Country <> 'United Kingdom'
GROUP BY Country
ORDER BY country_rev DESC      --FROM THIS WE CAN TELL THAT WE HAD THE HIGHEST REVENUE IN nETHERLANDS WITH AN AMOUNT OF 285,446


--THE NEXT IS TO LOOK AT THE TOP 10 CUSTOMERS PROVIDING THE HIGHEST REVENUE

SELECT TOP(10) CustomerID, ROUND(SUM(Revenue),0) AS customer_rev
FROM [dbo].[Online Retail]
GROUP BY CustomerID
ORDER BY customer_rev DESC      --FROM THIS WE CAN TELL THAT THE CUSTOMER WHO CONTRIBUTES THE HIGHES TO REVENUE IS CUSTOMER 14646 WITH 280,206


--FINALLY WE LOOK AT THE COUNTRY WITH THE HIGHEST DEMAND IN QUANTITY. THE AIM FOR THIS IS TO LOOK AT POSSIBILITY OF EXPANSION

SELECT Country, SUM(quantity) AS country_quantity
FROM [dbo].[Online Retail]
WHERE COUNTRY <> 'united Kingdom'
GROUP BY Country
ORDER BY country_quantity DESC   --FROM HERE WE CAN TELL THAT THE COUNTRY WITH THE HIGHEST DEMAND IS NETHERLANDS WITH A QUANTITY OF200937 IN DEMAND


